name: "Test Suite"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "wip/**" ]

jobs:
  unittest:
    name: "Unittest - rust-${{ matrix.rust }}@${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["nightly", "stable"]

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Install Rust Components"
      run: rustup default "${{ matrix.rust }}"
    - name: "Build Project"
      run: cargo build --verbose --all-targets
    - name: "Run Tests"
      run: cargo test --verbose

  crosstest:
    name: "Crosstest - rust-${{ matrix.rust }}@${{ matrix.os }} on ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
        target:
        - "aarch64-unknown-linux-gnu"
        - "armv7-unknown-linux-gnueabihf"
        - "i686-unknown-linux-gnu"
        - "riscv64gc-unknown-linux-gnu"

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Install Rust Components"
      run: rustup default "${{ matrix.rust }}"
    - name: "Install Cross"
      run: cargo install cross
    - name: "Build Project"
      run: cross build --verbose --all-targets --target "${{ matrix.target }}"
    - name: "Run Tests"
      run: cross test --verbose --target "${{ matrix.target }}"
